id = "hot-dog-stand"
name = "Hot Dog Stand"
version = "0.0.2"
schema_version = 1
authors = ["CoasterFan5"]
description = "Hot Dog Stand theme for Zed"
repository = "https://github.com/coasterfan5/hotdog-stand-zed"
